# Site settings
title: "James Goldie"
subtitle: "rensa.co"
email: "me@rensa.co"
url: https://rensa.co
baseurl: /blank-project
description: "PhD student (climate change + health). I also code and build things for fun and for social change."
twitter_username: rensa_co

# paginate: 5
# paginate_path: "/blog/page-:num"
google_analytics: UA-104057153-1
default_img: assets/me.jpg

# Profile settings
name: James Goldie
profile_img: assets/me.jpg
profile: "PhD student (climate change + health). I also code and build things for fun and for social change."

social:
  facebook: https://facebook.com/rensa
  twitter: https://twitter.com/rensa_co
  linkedin: https://au.linkedin.com/in/rensaco
  github: https://github.com/rensa
  stack-overflow: https://stackoverflow.com/story/rensa
  flask: https://www.researchgate.net/profile/James_Goldie2
  envelope-o: mailto:me@rensa.co
  key: https://keybase.io/rensa
  rss: https://rensa.co/feed.xml

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: "/:categories/:title/"

kramdown:
  smart_quotes: ["lsquo", "rsquo", "ldquo", "rdquo"]
  syntax_highlighter: rouge

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer, rouge]

# other notes for posts:
# - use my_css and my_js to include a custom style sheet or js
# - use ext_js (url: ) to include external js libs in the footer
# - use ext_js_head (url: ) to include external js libs in the head
# - use mast_mini: true to reduce the header size